### ISSUE TITLE
anki-editable `field` attribute is empty in Anki 2.1.55

### ISSUE THREAD

**Issue by Aquafina-water-bottle** [kleinerpirat/anki-css-injector#2]
It seems like the `field` attribute no longer works on the newest version of Anki.
For example, using the [Anki webview addon](https://ankiweb.net/shared/info/31746032), I get the following information:
```html
<anki-editable contenteditable="true" class="svelte-18uwveo isLin nightMode night_mode" field="" ord="7" editor="svelte" pointversion="55" notetype="JP Mining Note" mid="1637704315966" style="--editor-shrink-max-width:250px; --editor-shrink-max-height:125px;">TEXT<br></anki-editable>
```

**Comment by kleinerpirat** [comment]
Thanks for the report! I'll update my add-ons to 2.1.55 before Christmas.

**Comment by Aquafina-water-bottle** [comment]
Closed because it was fixed in the latest commit + uploaded to Ankiweb. Thanks for fixing it!

**Comment by kleinerpirat** [comment]
Sorry it took so long 😅
