### ISSUE TITLE
Can't inject css into certain views

### ISSUE THREAD

**Issue by h16nning** [kleinerpirat/anki-css-injector#5]
Hey @kleinerpirat,

I really love the idea of injecting css to customize anki. However, I couldn't get it to work following the guide provided. No matter what selectors I use, they have no effect. They don't even show up in the inspector. I tried editing both editor.css and field.css. I am using version 2.1.47. I disabled all other extensions.

What could cause my problem? Do you have any ideas?

Thanks in advance.

After updating to Qt6 I managed to inject to css into some views. But other views remain uneditable (e.g. the congrats "you learned all cards for today" menu). Is there a workaround?

**Comment by abdnh** [comment]
The add-on only works in the editor.
